import 'colors';
import { SignatureV4 } from '@smithy/signature-v4';
import { AppSyncEventWebSocketClientOptions } from './types.js';
export declare class AppSyncEventWebSocketClient {
    debug: boolean;
    private socket?;
    private options;
    private operations;
    private realtime_url;
    private host;
    private region;
    private signer;
    private connectionPromise?;
    private connectionResolver?;
    private connectionRejecter?;
    private keep_alive_timeout?;
    private connection_timeout_ms;
    constructor(options: AppSyncEventWebSocketClientOptions);
    initialize_signer(): SignatureV4;
    get is_connected(): boolean;
    private create_request;
    private get_signed_auth_headers;
    private create_connection_auth_subprotocol;
    connect(): Promise<void>;
    private handle_message;
    private send_message;
    private handle_keep_alive;
    private cleanup_connection;
    disconnect(): Promise<void>;
    subscribe(channel: string, on_data_callback: (data: any) => void): Promise<string>;
    publish(channel: string, events: any[]): Promise<any>;
    unsubscribe(subscription_id: string): Promise<any>;
}
